# Programa que leia algo pelo teclado e diga o tipo primitivo.
import time
algo = input('Digite algo: ')
print('Qual é o tipo?', (type(algo)))
time.sleep(2)
print('É numérico?', algo.isnumeric())
time.sleep(2)
print('É uma palavra?', algo.isalpha())
time.sleep(2)
print('É número ou letra?', algo.isalnum())
time.sleep(2)
print('É maiúsculo?', algo.isupper())
time.sleep(2)
print('É minúsculo?', algo.islower())
time.sleep(2)
print('É um dígito?', algo.isdigit())
time.sleep(2)
print('É decimal?', algo.isdecimal())
time.sleep(2)
print('Tem espaço?', algo.isspace())
time.sleep(2)
